<?php

/**
 * 16 進位色碼
 *
 * @var string[]
 */
define('HEX_COLOR', [

    # 粉紅色系
    'MediumVioletRed' => '#C71585',
    'DeepPink'        => '#FF1493',
    'PaleVioletRed'   => '#DB7093',
    'HotPink'         => '#FF69B4',
    'LightPink'       => '#FFB6C1',
    'Pink'            => '#FFC0CB',

    # 紅色系
    'DarkRed'     => '#8B0000',
    'Red'         => '#FF0000',
    'Firebrick'   => '#B22222',
    'Crimson'     => '#DC143C',
    'IndianRed'   => '#CD5C5C',
    'LightCoral'  => '#F08080',
    'Salmon'      => '#FA8072',
    'DarkSalmon'  => '#E9967A',
    'LightSalmon' => '#FFA07A',

    # 橘色系
    'OrangeRed'  => '#FF4500',
    'Tomato'     => '#FF6347',
    'DarkOrange' => '#FF8C00',
    'Coral'      => '#FF7F50',
    'Orange'     => '#FFA500',

    # 黃色系
    'DarkKhaki'            => '#BDB76B',
    'Gold'                 => '#FFD700',
    'Khaki'                => '#F0E68C',
    'PeachPuff'            => '#FFDAB9',
    'Yellow'               => '#FFFF00',
    'PaleGoldenrod'        => '#EEE8AA',
    'Moccasin'             => '#FFE4B5',
    'PapayaWhip'           => '#FFEFD5',
    'LightGoldenrodYellow' => '#FAFAD2',
    'LemonChiffon'         => '#FFFACD',
    'LightYellow'          => '#FFFFE0',

    # 棕色系
    'Maroon'         => '#800000',
    'Brown'          => '#A52A2A',
    'SaddleBrown'    => '#8B4513',
    'Sienna'         => '#A0522D',
    'Chocolate'      => '#D2691E',
    'DarkGoldenrod'  => '#B8860B',
    'Peru'           => '#CD853F',
    'RosyBrown'      => '#BC8F8F',
    'Goldenrod'      => '#DAA520',
    'SandyBrown'     => '#F4A460',
    'Tan'            => '#D2B48C',
    'Burlywood'      => '#DEB887',
    'Wheat'          => '#F5DEB3',
    'NavajoWhite'    => '#FFDEAD',
    'Bisque'         => '#FFE4C4',
    'BlanchedAlmond' => '#FFEBCD',
    'Cornsilk'       => '#FFF8DC',

    # 綠色系
    'DarkGreen' => '#006400',
    'Green' => '#008000',
    'DarkOliveGreen' => '#556B2F',
    'ForestGreen' => '#228B22',
    'SeaGreen' => '#2E8B57',
    'Olive' => '#808000',
    'OliveDrab' => '#6B8E23',
    'MediumSeaGreen' => '#3CB371',
    'LimeGreen' => '#32CD32',
    'Lime' => '#00FF00',
    'SpringGreen' => '#00FF7F',
    'MediumSpringGreen' => '#00FA9A',
    'DarkSeaGreen' => '#8FBC8F',
    'MediumAquamarine' => '#66CDAA',
    'YellowGreen' => '#9ACD32',
    'LawnGreen' => '#7CFC00',
    'Chartreuse' => '#7FFF00',
    'LightGreen' => '#90EE90',
    'GreenYellow' => '#ADFF2F',
    'PaleGreen' => '#98FB98',

    # 青色系
    'Teal' => '#008080',
    'DarkCyan' => '#008B8B',
    'LightSeaGreen' => '#20B2AA',
    'CadetBlue' => '#5F9EA0',
    'DarkTurquoise' => '#00CED1',
    'MediumTurquoise' => '#48D1CC',
    'Turquoise' => '#40E0D0',
    'Aqua' => '#00FFFF',
    'Cyan' => '#00FFFF',
    'Aquamarine' => '#7FFFD4',
    'PaleTurquoise' => '#AFEEEE',
    'LightCyan' => '#E0FFFF',

    # 藍色系
    'Navy' => '#000080',
    'DarkBlue' => '#00008B',
    'MediumBlue' => '#0000CD',
    'Blue' => '#0000FF',
    'MidnightBlue' => '#191970',
    'RoyalBlue' => '#4169E1',
    'SteelBlue' => '#4682B4',
    'DodgerBlue' => '#1E90FF',
    'DeepSkyBlue' => '#00BFFF',
    'CornflowerBlue' => '#6495ED',
    'SkyBlue' => '#87CEEB',
    'LightSkyBlue' => '#87CEFA',
    'LightSteelBlue' => '#B0C4DE',
    'LightBlue' => '#ADD8E6',
    'PowderBlue' => '#B0E0E6',

    # 紫色系
    'Indigo' => '#4B0082',
    'Purple' => '#800080',
    'DarkMagenta' => '#8B008B',
    'DarkViolet' => '#9400D3',
    'DarkSlateBlue' => '#483D8B',
    'RebeccaPurple' => '#663399',
    'BlueViolet' => '#8A2BE2',
    'DarkOrchid' => '#9932CC',
    'Fuchsia' => '#FF00FF',
    'Magenta' => '#FF00FF',
    'SlateBlue' => '#6A5ACD',
    'MediumSlateBlue' => '#7B68EE',
    'MediumOrchid' => '#BA55D3',
    'MediumPurple' => '#9370DB',
    'Orchid' => '#DA70D6',
    'Violet' => '#EE82EE',
    'Plum' => '#DDA0DD',
    'Thistle' => '#D8BFD8',
    'Lavender' => '#E6E6FA',

    # 白色系
    'MistyRose' => '#FFE4E1',
    'AntiqueWhite' => '#FAEBD7',
    'Linen' => '#FAF0E6',
    'Beige' => '#F5F5DC',
    'WhiteSmoke' => '#F5F5F5',
    'LavenderBlush' => '#FFF0F5',
    'OldLace' => '#FDF5E6',
    'AliceBlue' => '#F0F8FF',
    'Seashell' => '#FFF5EE',
    'GhostWhite' => '#F8F8FF',
    'Honeydew' => '#F0FFF0',
    'FloralWhite' => '#FFFAF0',
    'Azure' => '#F0FFFF',
    'MintCream' => '#F5FFFA',
    'Snow' => '#FFFAFA',
    'Ivory' => '#FFFFF0',
    'White' => '#FFFFFF',

    # 灰黑色系
    'Black' => '#000000',
    'DarkSlateGray' => '#2F4F4F',
    'DimGray' => '#696969',
    'SlateGray' => '#708090',
    'Gray' => '#808080',
    'LightSlateGray' => '#778899',
    'DarkGray' => '#A9A9A9',
    'Silver' => '#C0C0C0',
    'LightGray' => '#D3D3D3',
    'Gainsboro' => '#DCDCDC',

]);
